server {
    listen 80;
    server_name coursescheduler.engr.uconn.edu;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name coursescheduler.engr.uconn.edu;

    ssl_certificate     /etc/letsencrypt/live/coursescheduler.engr.uconn.edu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coursescheduler.engr.uconn.edu/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Frontend
    location / {
        proxy_pass http://nextjs-frontend:3000/;
        include /etc/nginx/proxy_params;
    }

    # Node backend
    location /GetClasses {
        proxy_pass http://node-backend:5178/;
        include /etc/nginx/proxy_params;
    }

    # .NET backend
    location /Schedule {
        proxy_pass http://dotnet-backend:5041/;
        include /etc/nginx/proxy_params;
    }
}
