import React, { useState } from "react";
import { Button, Modal, Box, Typography } from "@mui/material";


function Cart_block() {

    // const items = ["Apple", "Banana", "Cherry"];
    const items = ["CSE 1010", "CSE 2050", "CSE 3150", "CSE 3666"]

    const data = {
        "CSE 1010": {
            "4376": {
                "Enrollment Capacity": 200,
                "Enrollment Total": 0,
                "Professor": "Olga Glebova (PI)",
                "Seats Available": null,
                "acad_career": "UGRD",
                "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":false,\"hidden\":true,\"options\":[{\"value\":\"\",\"label\":\"NA\",\"default\":true,\"selected\":\"selected\"}]}}",
                "code": "CSE 1010",
                "crn": "4376",
                "end_date": "2025-12-05",
                "hide": "",
                "instr": "",
                "instructorresult_html": "",
                "isCancelled": "",
                "is_enroll_section": "0",
                "key": "7643",
                "linked_crns": "4377,4379,4380,4381,4382,4383,4386,4387,4419,4420",
                "meetingTimes": "[{\"meet_day\":\"0\",\"start_time\":\"1430\",\"end_time\":\"1520\"}]",
                "meets": "M 2:30-3:20p",
                "mpkey": "2682",
                "no": "001",
                "open_enroll": "",
                "required": {
                    "LAB": {
                        "001": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4379",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7644",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"800\",\"end_time\":\"950\"}]",
                            "meets": "W 8-9:50a",
                            "mpkey": "3307",
                            "no": "001L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "002": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4380",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7645",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "W 10-11:50a",
                            "mpkey": "4431",
                            "no": "002L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "003": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4377",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7646",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1515\",\"end_time\":\"1705\"}]",
                            "meets": "W 3:15-5:05p",
                            "mpkey": "4432",
                            "no": "003L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "004": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4381",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7647",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1715\",\"end_time\":\"1905\"}]",
                            "meets": "W 5:15-7:05p",
                            "mpkey": "4433",
                            "no": "004L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "005": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4382",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7648",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1315\",\"end_time\":\"1505\"}]",
                            "meets": "W 1:15-3:05p",
                            "mpkey": "4435",
                            "no": "005L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "006": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4383",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7649",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"915\",\"end_time\":\"1105\"}]",
                            "meets": "W 9:15-11:05a",
                            "mpkey": "4434",
                            "no": "006L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "007": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4386",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7650",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1115\",\"end_time\":\"1305\"}]",
                            "meets": "W 11:15a-1:05p",
                            "mpkey": "3454",
                            "no": "007L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "008": {
                            "Enrollment Capacity": 19,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4387",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7651",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "W 10-11:50a",
                            "mpkey": "4431",
                            "no": "008L",
                            "open_enroll": "",
                            "reserved": "19 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "064": {
                            "Enrollment Capacity": 19,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4419",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7685",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1400\",\"end_time\":\"1550\"}]",
                            "meets": "W 2-3:50p",
                            "mpkey": "4922",
                            "no": "064L",
                            "open_enroll": "",
                            "reserved": "19 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "065": {
                            "Enrollment Capacity": 19,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4420",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7686",
                            "linked_crns": "4376",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1600\",\"end_time\":\"1750\"}]",
                            "meets": "W 4-5:50p",
                            "mpkey": "3212",
                            "no": "065L",
                            "open_enroll": "",
                            "reserved": "19 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        }
                    }
                },
                "reserved": "",
                "schd": "LEC",
                "srcdb": "1258",
                "start_date": "2025-08-25",
                "stat": "A",
                "title": "Introduction to Computing for Engineers",
                "total": "68"
            },
            "4384": {
                "Enrollment Capacity": 200,
                "Enrollment Total": 0,
                "Professor": "Olga Glebova (TC)",
                "Seats Available": null,
                "acad_career": "UGRD",
                "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":false,\"hidden\":true,\"options\":[{\"value\":\"\",\"label\":\"NA\",\"default\":true,\"selected\":\"selected\"}]}}",
                "code": "CSE 1010",
                "crn": "4384",
                "end_date": "2025-12-05",
                "hide": "",
                "instr": "",
                "instructorresult_html": "",
                "isCancelled": "",
                "is_enroll_section": "0",
                "key": "7652",
                "linked_crns": "4385,4388,4389,4390,4391,4392,4393,4394,4395,4418",
                "meetingTimes": "[{\"meet_day\":\"4\",\"start_time\":\"1430\",\"end_time\":\"1520\"}]",
                "meets": "F 2:30-3:20p",
                "mpkey": "2591",
                "no": "021",
                "open_enroll": "",
                "required": {
                    "LAB": {
                        "021": {
                            "Enrollment Capacity": 19,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4388",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7653",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"0\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "M 10-11:50a",
                            "mpkey": "4137",
                            "no": "021L",
                            "open_enroll": "",
                            "reserved": "19 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "022": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4385",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7654",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"0\",\"start_time\":\"1200\",\"end_time\":\"1350\"}]",
                            "meets": "M 12-1:50p",
                            "mpkey": "5214",
                            "no": "022L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "023": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4389",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7655",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"0\",\"start_time\":\"1400\",\"end_time\":\"1550\"}]",
                            "meets": "M 2-3:50p",
                            "mpkey": "3670",
                            "no": "023L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "024": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4390",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7656",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "Th 10-11:50a",
                            "mpkey": "3360",
                            "no": "024L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "025": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4391",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7657",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"0\",\"start_time\":\"1600\",\"end_time\":\"1750\"}]",
                            "meets": "M 4-5:50p",
                            "mpkey": "5416",
                            "no": "025L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "026": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4392",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7658",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1600\",\"end_time\":\"1750\"}]",
                            "meets": "Th 4-5:50p",
                            "mpkey": "4043",
                            "no": "026L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "027": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4393",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7659",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1400\",\"end_time\":\"1550\"}]",
                            "meets": "Th 2-3:50p",
                            "mpkey": "3364",
                            "no": "027L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "028": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4394",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7660",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1500\",\"end_time\":\"1650\"}]",
                            "meets": "Th 3-4:50p",
                            "mpkey": "4436",
                            "no": "028L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "029": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4395",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7661",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "W 10-11:50a",
                            "mpkey": "4431",
                            "no": "029L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "063": {
                            "Enrollment Capacity": 19,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (TC)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4418",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7684",
                            "linked_crns": "4384",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1200\",\"end_time\":\"1350\"}]",
                            "meets": "W 12-1:50p",
                            "mpkey": "4921",
                            "no": "063L",
                            "open_enroll": "",
                            "reserved": "19 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        }
                    }
                },
                "reserved": "",
                "schd": "LEC",
                "srcdb": "1258",
                "start_date": "2025-08-25",
                "stat": "A",
                "title": "Introduction to Computing for Engineers",
                "total": "68"
            },
            "4396": {
                "Enrollment Capacity": 200,
                "Enrollment Total": 0,
                "Professor": "Olga Glebova (PI)",
                "Seats Available": null,
                "acad_career": "UGRD",
                "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":false,\"hidden\":true,\"options\":[{\"value\":\"\",\"label\":\"NA\",\"default\":true,\"selected\":\"selected\"}]}}",
                "code": "CSE 1010",
                "crn": "4396",
                "end_date": "2025-12-05",
                "hide": "",
                "instr": "",
                "instructorresult_html": "",
                "isCancelled": "",
                "is_enroll_section": "0",
                "key": "7662",
                "linked_crns": "4397,4398,4399,4400,4401,4402,4403,4415,4416,4417",
                "meetingTimes": "[{\"meet_day\":\"0\",\"start_time\":\"1325\",\"end_time\":\"1415\"}]",
                "meets": "M 1:25-2:15p",
                "mpkey": "2744",
                "no": "031",
                "open_enroll": "",
                "required": {
                    "LAB": {
                        "031": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4397",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7663",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "Th 10-11:50a",
                            "mpkey": "3360",
                            "no": "031L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "032": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4398",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7664",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "Th 10-11:50a",
                            "mpkey": "3360",
                            "no": "032L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "033": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4399",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7665",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1200\",\"end_time\":\"1350\"}]",
                            "meets": "Th 12-1:50p",
                            "mpkey": "3361",
                            "no": "033L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "034": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4400",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7666",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1300\",\"end_time\":\"1450\"}]",
                            "meets": "Th 1-2:50p",
                            "mpkey": "3378",
                            "no": "034L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "035": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4401",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7667",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1700\",\"end_time\":\"1850\"}]",
                            "meets": "Th 5-6:50p",
                            "mpkey": "4284",
                            "no": "035L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "036": {
                            "Enrollment Capacity": 19,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4402",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7668",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1300\",\"end_time\":\"1450\"}]",
                            "meets": "Th 1-2:50p",
                            "mpkey": "3378",
                            "no": "036L",
                            "open_enroll": "",
                            "reserved": "19 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "039": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4403",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7669",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"0\",\"start_time\":\"1600\",\"end_time\":\"1750\"}]",
                            "meets": "M 4-5:50p",
                            "mpkey": "5416",
                            "no": "039L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "053": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4415",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7681",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1500\",\"end_time\":\"1650\"}]",
                            "meets": "T 3-4:50p",
                            "mpkey": "4437",
                            "no": "053L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "054": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4416",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7682",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1700\",\"end_time\":\"1850\"}]",
                            "meets": "T 5-6:50p",
                            "mpkey": "4282",
                            "no": "054L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "061": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4417",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7683",
                            "linked_crns": "4396",
                            "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"800\",\"end_time\":\"950\"}]",
                            "meets": "W 8-9:50a",
                            "mpkey": "3307",
                            "no": "061L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        }
                    }
                },
                "reserved": "",
                "schd": "LEC",
                "srcdb": "1258",
                "start_date": "2025-08-25",
                "stat": "A",
                "title": "Introduction to Computing for Engineers",
                "total": "68"
            },
            "4404": {
                "Enrollment Capacity": 200,
                "Enrollment Total": 0,
                "Professor": "Olga Glebova (PI)",
                "Seats Available": null,
                "acad_career": "UGRD",
                "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":false,\"hidden\":true,\"options\":[{\"value\":\"\",\"label\":\"NA\",\"default\":true,\"selected\":\"selected\"}]}}",
                "code": "CSE 1010",
                "crn": "4404",
                "end_date": "2025-12-05",
                "hide": "",
                "instr": "",
                "instructorresult_html": "",
                "isCancelled": "",
                "is_enroll_section": "0",
                "key": "7670",
                "linked_crns": "4405,4406,4407,4408,4409,4410,4411,4412,4413,4414",
                "meetingTimes": "[{\"meet_day\":\"2\",\"start_time\":\"1430\",\"end_time\":\"1520\"}]",
                "meets": "W 2:30-3:20p",
                "mpkey": "2471",
                "no": "041",
                "open_enroll": "",
                "required": {
                    "LAB": {
                        "041": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (PI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4405",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7671",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "T 10-11:50a",
                            "mpkey": "3464",
                            "no": "041L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "042": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4406",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7672",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1300\",\"end_time\":\"1450\"}]",
                            "meets": "T 1-2:50p",
                            "mpkey": "3465",
                            "no": "042L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "043": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4407",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7673",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1500\",\"end_time\":\"1650\"}]",
                            "meets": "T 3-4:50p",
                            "mpkey": "4437",
                            "no": "043L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "044": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4408",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7674",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1700\",\"end_time\":\"1850\"}]",
                            "meets": "T 5-6:50p",
                            "mpkey": "4282",
                            "no": "044L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "045": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4409",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7675",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"800\",\"end_time\":\"950\"}]",
                            "meets": "T 8-9:50a",
                            "mpkey": "3375",
                            "no": "045L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "046": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4410",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7676",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"800\",\"end_time\":\"950\"}]",
                            "meets": "Th 8-9:50a",
                            "mpkey": "3359",
                            "no": "046L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "047": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4411",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7677",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1500\",\"end_time\":\"1650\"}]",
                            "meets": "Th 3-4:50p",
                            "mpkey": "4436",
                            "no": "047L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "048": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4412",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7678",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"3\",\"start_time\":\"1700\",\"end_time\":\"1850\"}]",
                            "meets": "Th 5-6:50p",
                            "mpkey": "4284",
                            "no": "048L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "051": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (PI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4413",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7679",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1000\",\"end_time\":\"1150\"}]",
                            "meets": "T 10-11:50a",
                            "mpkey": "3464",
                            "no": "051L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        },
                        "052": {
                            "Enrollment Capacity": 20,
                            "Enrollment Total": 0,
                            "Professor": "Olga Glebova (SI)",
                            "Seats Available": null,
                            "acad_career": "UGRD",
                            "cart_opts": "{\"credit_hrs\":{\"cartField\":\"p_hours\",\"enabled\":true,\"options\":[{\"value\":\"3\",\"label\":\"3\",\"default\":true,\"selected\":\"selected\"}],\"hidden\":true},\"grade_mode\":{\"cartField\":\"p_gmod\",\"enabled\":true,\"options\":[{\"value\":\"GRD\",\"label\":\"Graded Numeric\",\"default\":true,\"selected\":\"selected\"}]}}",
                            "code": "CSE 1010",
                            "crn": "4414",
                            "end_date": "2025-12-05",
                            "hide": "",
                            "instr": "",
                            "instructorresult_html": "",
                            "isCancelled": "",
                            "is_enroll_section": "1",
                            "key": "7680",
                            "linked_crns": "4404",
                            "meetingTimes": "[{\"meet_day\":\"1\",\"start_time\":\"1300\",\"end_time\":\"1450\"}]",
                            "meets": "T 1-2:50p",
                            "mpkey": "3465",
                            "no": "052L",
                            "open_enroll": "",
                            "reserved": "20 for RC ENGR Students",
                            "schd": "LAB",
                            "srcdb": "1258",
                            "start_date": "2025-08-25",
                            "stat": "A",
                            "title": "Introduction to Computing for Engineers",
                            "total": "68"
                        }
                    }
                },
                "reserved": "",
                "schd": "LEC",
                "srcdb": "1258",
                "start_date": "2025-08-25",
                "stat": "A",
                "title": "Introduction to Computing for Engineers",
                "total": "68"
            }
        }
    }

    const firstKey = Object.keys(data)[0]

    const [open, setOpen] = useState(false);
  
    const handleOpen = () => setOpen(true);
    const handleClose = () => setOpen(false);

    const style = {
        position: "absolute",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -50%)",
        width: 400,
        bgcolor: "background.paper",
        border: "2px solid #000",
        boxShadow: 24,
        p: 4,
      };

    return (
        <div className="h-[50rem] flex flex-col justify-top items-center bg-green-500 size-full">
            <h1 className="text-5xl m-20">Class List</h1>
            <div className="h-[80%] mt-auto border-2 size-full">
            <ul className="flex flex-col items-center w-full p-4 border">
                {items.map((item, index) => (
                    <li key={index} className="flex items-center w-full p-4 border">
                    <div className="flex items-center gap-3">

                        <Button onClick={handleOpen}>Info</Button>
                        <Modal
                        open={open}
                        onClose={handleClose}
                        aria-labelledby="modal-modal-title"
                        aria-describedby="modal-modal-description"
                        >
                        <Box sx={style}>
                            <Typography id="modal-modal-title" variant="h6" component="h2">
                            Text in a modal
                            </Typography>
                            <Typography id="modal-modal-description" sx={{ mt: 2 }}>
                                Class: {Object.keys(data)[0]}
                            </Typography>
                        </Box>
                        </Modal>

                        <div className="text-2xl border px-2">{item}</div>
                    </div>
                    <button className="text-xl border ml-auto px-2">
                        delete
                    </button>
                    </li>     
                ))}
            </ul>
            <div className="text-5xl text-center mt-20">
                Generate
            </div>
            </div>
        </div>
    )
}
  
  export default Cart_block
  