import React, { useState } from "react";
import Select from "react-select";

import { customStyles } from "./Styles/searchbar_style.jsx";



const options = [
  { value: "Any", label: "Any" },
  { value: "Asian and Asian American Studies", label: "Asian and Asian American Studies (AAAS)" },
  { value: "Accounting", label: "Accounting (ACCT)" },
  { value: "American English Language Institute", label: "American English Language Institute (AELI)" },
  { value: "Africana Studies", label: "Africana Studies (AFRA)" },
  { value: "Agriculture and Natural Resources", label: "Agriculture and Natural Resources (AGNR)" },
  { value: "Allied Health Sciences", label: "Allied Health Sciences (AH)" },
  { value: "Agriculture, Health and Natural Resources", label: "Agriculture, Health and Natural Resources (AHNR)" },
  { value: "Air Force Studies", label: "Air Force Studies (AIRF)" },
  { value: "Applied Linguistics and Discourse Studies", label: "Applied Linguistics and Discourse Studies (ALDS)" },
  { value: "Advanced Manufacturing for Energy Systems", label: "Advanced Manufacturing for Energy Systems (AMES)" },
  { value: "American Studies", label: "American Studies (AMST)" },
  { value: "Anesthesiology", label: "Anesthesiology (ANES)" },
  { value: "Animal Science", label: "Animal Science (ANSC)" },
  { value: "Anthropology", label: "Anthropology (ANTH)" },
  { value: "Arabic", label: "Arabic (ARAB)" },
  { value: "Agricultural and Resource Economics", label: "Agricultural and Resource Economics (ARE)" },
  { value: "Arabic and Islamic Studies", label: "Arabic and Islamic Studies (ARIS)" },
  { value: "Art", label: "Art (ART)" },
  { value: "Art History", label: "Art History (ARTH)" },
  { value: "American Sign Language", label: "American Sign Language (ASLN)" },
  { value: "Business Administration", label: "Business Administration (BADM)" },
  { value: "Basics (Social Work)", label: "Basics (Social Work) (BASC)" },
  { value: "Biological Sciences", label: "Biological Sciences (BIOL)" },
  { value: "Biostatistics", label: "Biostatistics (BIST)" },
  { value: "Business Law", label: "Business Law (BLAW)" },
  { value: "Biomedical Engineering", label: "Biomedical Engineering (BME)" },
  { value: "Dental Basic Medical Sciences", label: "Dental Basic Medical Sciences (BSCI)" },
  { value: "Business", label: "Business (BUSN)" },
  { value: "Classics and Ancient Mediterranean Studies", label: "Classics and Ancient Mediterranean Studies (CAMS)" },
  { value: "Clinical Dental Science", label: "Clinical Dental Science (CDSC)" },
  { value: "Civil Engineering", label: "Civil Engineering (CE)" },
  { value: "COOP Education Work Placement", label: "COOP Education Work Placement (CEWP)" },
  { value: "Chemical Engineering", label: "Chemical Engineering (CHEG)" },
  { value: "Chemistry", label: "Chemistry (CHEM)" },
  { value: "Chinese", label: "Chinese (CHIN)" },
  { value: "Comparative Literary and Cultural Studies", label: "Comparative Literary and Cultural Studies (CLCS)" },
  { value: "Clinical", label: "Clinical (CLIN)" },
  { value: "Clinical and Translational Research", label: "Clinical and Translational Research (CLTR)" },
  { value: "Cognitive Science", label: "Cognitive Science (COGS)" },
  { value: "Communication", label: "Communication (COMM)" },
  { value: "Community Organization (Social Work)", label: "Community Organization (Social Work) (CORG)" },
  { value: "Computer Science and Engineering", label: "Computer Science and Engineering (CSE)" },
  { value: "Dental Science", label: "Dental Science (DENT)" },
  { value: "Dental Residency and Fellowship Program", label: "Dental Residency and Fellowship Program (DERE)" },
  { value: "Dermatology", label: "Dermatology (DERM)" },
  { value: "Diagnostic Genetic Sciences", label: "Diagnostic Genetic Sciences (DGS)" },
  { value: "Dietetics", label: "Dietetics (DIET)" },
  { value: "Digital Media and Design", label: "Digital Media and Design (DMD)" },
  { value: "Dramatic Arts", label: "Dramatic Arts (DRAM)" },
  { value: "Statistical Data Science and Analysis", label: "Statistical Data Science and Analysis (DSDA)" },
  { value: "Direct Service Elective (Social Work)", label: "Direct Service Elective (Social Work) (DSEL)" },
  { value: "Electrical and Computer Engineering", label: "Electrical and Computer Engineering (ECE)" },
  { value: "Economics", label: "Economics (ECON)" },
  { value: "Education Curriculum and Instruction", label: "Education Curriculum and Instruction (EDCI)" },
  { value: "Educational Leadership", label: "Educational Leadership (EDLR)" },
  { value: "Ecology and Evolutionary Biology", label: "Ecology and Evolutionary Biology (EEB)" },
  { value: "Education", label: "Education (EGEN)" },
  { value: "Executive MBA", label: "Executive MBA (EMBA)" },
  { value: "Emergency Medicine", label: "Emergency Medicine (EMED)" },
  { value: "English", label: "English (ENGL)" },
  { value: "Engineering", label: "Engineering (ENGR)" },
  { value: "Environmental Engineering", label: "Environmental Engineering (ENVE)" },
  { value: "Environmental Sciences", label: "Environmental Sciences (ENVS)" },
  { value: "Educational Psychology", label: "Educational Psychology (EPSY)" },
  { value: "Earth Sciences", label: "Earth Sciences (ERTH)" },
  { value: "European Studies", label: "European Studies (ES)" },
  { value: "Environmental Studies", label: "Environmental Studies (EVST)" },
  { value: "Exploratory", label: "Exploratory (EXPL)" },
  { value: "Foundational Dental Science", label: "Foundational Dental Science (FDSC)" },
  { value: "Field Education (Social Work)", label: "Field Education (Social Work) (FED)" },
  { value: "Family Medicine", label: "Family Medicine (FMED)" },
  { value: "Finance", label: "Finance (FNCE)" },
  { value: "French", label: "French (FREN)" },
  { value: "Geography", label: "Geography (GEOG)" },
  { value: "German", label: "German (GERM)" },
  { value: "General and Professional Studies", label: "General and Professional Studies (GPS)" },
  { value: "Graduate School", label: "Graduate School (GRAD)" },
  { value: "Human Behavior Elective", label: "Human Behavior Elective (HBEL)" },
  { value: "Hartford Consortium For Higher Education", label: "Hartford Consortium For Higher Education (HCHE)" },
  { value: "Healthcare Management and Insurance Studies", label: "Healthcare Management and Insurance Studies (HCMI)" },
  { value: "Human Development and Family Sciences", label: "Human Development and Family Sciences (HDFS)" },
  { value: "Hebrew and Judaic Studies", label: "Hebrew and Judaic Studies (HEJS)" },
  { value: "History", label: "History (HIST)" },
  { value: "Human Rights", label: "Human Rights (HRTS)" },
  { value: "Individuals, Groups, and Families (Social Work)", label: "Individuals, Groups, and Families (Social Work) (IGFP)" },
  { value: "Italian Literature and Cultural Studies", label: "Italian Literature and Cultural Studies (ILCS)" },
  { value: "Internal Medicine", label: "Internal Medicine (IMED)" },
  { value: "Institute of Materials Science", label: "Institute of Materials Science (IMS)" },
  { value: "India Studies", label: "India Studies (INDS)" },
  { value: "Interdepartmental", label: "Interdepartmental (INTD)" },
  { value: "International Studies", label: "International Studies (INTS)" },
  { value: "Irish", label: "Irish (IRIS)" },
  { value: "Independent Study (Social Work)", label: "Independent Study (Social Work) (IS)" },
  { value: "Institute for Systems Genomics", label: "Institute for Systems Genomics (ISG)" },
  { value: "Japanese", label: "Japanese (JAPN)" },
  { value: "Journalism", label: "Journalism (JOUR)" },
  { value: "Kinesiology", label: "Kinesiology (KINS)" },
  { value: "Korean", label: "Korean (KORE)" },
  { value: "Landscape Architecture", label: "Landscape Architecture (LAND)" },
  { value: "Law", label: "Law (LAW)" },
  { value: "Literatures, Cultures, and Languages", label: "Literatures, Cultures, and Languages (LCL)" },
  { value: "Linguistics", label: "Linguistics (LING)" },
  { value: "Latino and Latin American Studies", label: "Latino and Latin American Studies (LLAS)" },
  { value: "School of Medicine", label: "School of Medicine (M)" },
  { value: "Marine Sciences", label: "Marine Sciences (MARN)" },
  { value: "Maritime Studies", label: "Maritime Studies (MAST)" },
  { value: "Mathematics", label: "Mathematics (MATH)" },
  { value: "Molecular and Cell Biology", label: "Molecular and Cell Biology (MCB)" },
  { value: "Mechanical Engineering", label: "Mechanical Engineering (ME)" },
  { value: "Medical Science", label: "Medical Science (MEDS)" },
  { value: "Management and Engineering for Manufacturing", label: "Management and Engineering for Manufacturing (MEM)" },
  { value: "Management and Entrepreneurship", label: "Management and Entrepreneurship (MENT)" },
  { value: "Manufacturing Engineering", label: "Manufacturing Engineering (MFGE)" },
  { value: "Modern Greek", label: "Modern Greek (MGRK)" },
  { value: "Military Science", label: "Military Science (MISI)" },
  { value: "Marketing", label: "Marketing (MKTG)" },
  { value: "Medical Laboratory Sciences", label: "Medical Laboratory Sciences (MLSC)" },
  { value: "Materials Science and Engineering", label: "Materials Science and Engineering (MSE)" },
  { value: "Music", label: "Music (MUSI)" },
  { value: "Neurology", label: "Neurology (NEUR)" },
  { value: "Natural Resources and the Environment", label: "Natural Resources and the Environment (NRE)" },
  { value: "Nursing", label: "Nursing (NURS)" },
  { value: "Nutritional Sciences", label: "Nutritional Sciences (NUSC)" },
  { value: "OBGYN", label: "OBGYN (OBGY)" },
  { value: "Off Campus", label: "Off Campus (OFFC)" },
  { value: "OMFS", label: "OMFS (OMFS)" },
  { value: "Operations and Information Management", label: "Operations and Information Management (OPIM)" },
  { value: "Orthopaedic", label: "Orthopaedic (ORTH)" },
  { value: "Occupational Safety and Health", label: "Occupational Safety and Health (OSH)" },
  { value: "Pathobiology", label: "Pathobiology (PATH)" },
  { value: "Pediatrics", label: "Pediatrics (PEDS)" },
  { value: "Pharmacy - PHAR", label: "Pharmacy - PHAR (PHAR)" },
  { value: "Philosophy", label: "Philosophy (PHIL)" },
  { value: "Pharmacy - PHRX", label: "Pharmacy - PHRX (PHRX)" },
  { value: "Physics", label: "Physics (PHYS)" },
  { value: "Plant Science", label: "Plant Science (PLSC)" },
  { value: "Physiology and Neurobiology", label: "Physiology and Neurobiology (PNB)" },
  { value: "Political Science", label: "Political Science (POLS)" },
  { value: "Polymer Science and Engineering", label: "Polymer Science and Engineering (POLY)" },
  { value: "Policy Practice (Social Work)", label: "Policy Practice (Social Work) (POPR)" },
  { value: "Portuguese", label: "Portuguese (PORT)" },
  { value: "Public Policy", label: "Public Policy (PP)" },
  { value: "Psychiatry", label: "Psychiatry (PSCH)" },
  { value: "Psychological Sciences", label: "Psychological Sciences (PSYC)" },
  { value: "Physical Therapy", label: "Physical Therapy (PT)" },
  { value: "Pathology", label: "Pathology (PTHO)" },
  { value: "Public Health", label: "Public Health (PUBH)" },
  { value: "Radiology", label: "Radiology (RADS)" },
  { value: "Research (Social Work)", label: "Research (Social Work) (RSCH)" },
  { value: "Agriculture (RH)", label: "Agriculture (RH) (SAAG)" },
  { value: "Animal Science (RH)", label: "Animal Science (RH) (SAAS)" },
  { value: "Natural Resources and the Environment (RH)", label: "Natural Resources and the Environment (RH) (SANR)" },
  { value: "Pathobiology (RH)", label: "Pathobiology (RH) (SAPB)" },
  { value: "Plant Science (RH)", label: "Plant Science (RH) (SAPL)" },
  { value: "Agricultural and Resource Economics (RH)", label: "Agricultural and Resource Economics (RH) (SARE)" },
  { value: "Systems Engineering", label: "Systems Engineering (SE)" },
  { value: "Speech, Language and Hearing Science", label: "Speech, Language and Hearing Science (SLHS)" },
  { value: "Sociology", label: "Sociology (SOCI)" },
  { value: "SOWK - Social Work", label: "SOWK - Social Work (SOWK)" },
  { value: "Spanish", label: "Spanish (SPAN)" },
  { value: "Sustainable Plant and Soil Systems", label: "Sustainable Plant and Soil Systems (SPSS)" },
  { value: "Special Topics (Social Work)", label: "Special Topics (Social Work) (SPTP)" },
  { value: "SSW - Social Work", label: "SSW - Social Work (SSW)" },
  { value: "Statistics", label: "Statistics (STAT)" },
  { value: "Surgery", label: "Surgery (SURG)" },
  { value: "Social Work Elective", label: "Social Work Elective (SWEL)" },
  { value: "Transformation", label: "Transformation (TRNS)" },
  { value: "Translation Studies", label: "Translation Studies (TRST)" },
  { value: "University", label: "University (UNIV)" },
  { value: "Urban and Community Studies", label: "Urban and Community Studies (URBN)" },
  { value: "Women's, Gender, and Sexuality Studies", label: "Women's, Gender, and Sexuality Studies (WGSS)" }
];
  








const SearchableDropdown = ({filter, setfilter}) => {

  const handleDropdownChange = (selectedOption) => {
    setfilter(String(selectedOption["value"]));
};

  return (
    <div className="rounded z-1  text-start text-black inline-block relative">
      <Select value={filter}
        onChange={handleDropdownChange}
        options={options}  styles={customStyles} placeholder={filter}> 
        
        </Select>
    </div>
  );
};

export default SearchableDropdown;
