import React, { useState } from "react";
import Select from "react-select";

import { customStyles } from "./Styles/searchbar_style.jsx";



const options = [
    { value: "Any", label: "Any" },
    { value: "Asian and Asian American Studies", label: "Asian and Asian American Studies" },
    { value: "Accounting", label: "Accounting" },
    { value: "American English Language Institute", label: "American English Language Institute" },
    { value: "Africana Studies", label: "Africana Studies" },
    { value: "Agriculture and Natural Resources", label: "Agriculture and Natural Resources" },
    { value: "Allied Health Sciences", label: "Allied Health Sciences" },
    { value: "Agriculture, Health and Natural Resources", label: "Agriculture, Health and Natural Resources" },
    { value: "Air Force Studies", label: "Air Force Studies" },
    { value: "Applied Linguistics and Discourse Studies", label: "Applied Linguistics and Discourse Studies" },
    { value: "Advanced Manufacturing for Energy Systems", label: "Advanced Manufacturing for Energy Systems" },
    { value: "American Studies", label: "American Studies" },
    { value: "Anesthesiology", label: "Anesthesiology" },
    { value: "Animal Science", label: "Animal Science" },
    { value: "Anthropology", label: "Anthropology" },
    { value: "Arabic", label: "Arabic" },
    { value: "Agricultural and Resource Economics", label: "Agricultural and Resource Economics" },
    { value: "Arabic and Islamic Studies", label: "Arabic and Islamic Studies" },
    { value: "Art", label: "Art" },
    { value: "Art History", label: "Art History" },
    { value: "American Sign Language", label: "American Sign Language" },
    { value: "Business Administration", label: "Business Administration" },
    { value: "Basics (Social Work)", label: "Basics (Social Work)" },
    { value: "Biological Sciences", label: "Biological Sciences" },
    { value: "Biostatistics", label: "Biostatistics" },
    { value: "Business Law", label: "Business Law" },
    { value: "Biomedical Engineering", label: "Biomedical Engineering" },
    { value: "Dental Basic Medical Sciences", label: "Dental Basic Medical Sciences" },
    { value: "Business", label: "Business" },
    { value: "Classics and Ancient Mediterranean Studies", label: "Classics and Ancient Mediterranean Studies" },
    { value: "Clinical Dental Science", label: "Clinical Dental Science" },
    { value: "Civil Engineering", label: "Civil Engineering" },
    { value: "COOP Education Work Placement", label: "COOP Education Work Placement" },
    { value: "Chemical Engineering", label: "Chemical Engineering" },
    { value: "Chemistry", label: "Chemistry" },
    { value: "Chinese", label: "Chinese" },
    { value: "Comparative Literary and Cultural Studies", label: "Comparative Literary and Cultural Studies" },
    { value: "Clinical", label: "Clinical" },
    { value: "Clinical and Translational Research", label: "Clinical and Translational Research" },
    { value: "Cognitive Science", label: "Cognitive Science" },
    { value: "Communication", label: "Communication" },
    { value: "Community Organization (Social Work)", label: "Community Organization (Social Work)" },
    { value: "Computer Science and Engineering", label: "Computer Science and Engineering" },
    { value: "Dental Science", label: "Dental Science" },
    { value: "Dental Residency and Fellowship Program", label: "Dental Residency and Fellowship Program" },
    { value: "Dermatology", label: "Dermatology" },
    { value: "Diagnostic Genetic Sciences", label: "Diagnostic Genetic Sciences" },
    { value: "Dietetics", label: "Dietetics" },
    { value: "Digital Media and Design", label: "Digital Media and Design" },
    { value: "Dramatic Arts", label: "Dramatic Arts" },
    { value: "Statistical Data Science and Analysis", label: "Statistical Data Science and Analysis" },
    { value: "Direct Service Elective (Social Work)", label: "Direct Service Elective (Social Work)" },
    { value: "Electrical and Computer Engineering", label: "Electrical and Computer Engineering" },
    { value: "Economics", label: "Economics" },
    { value: "Education Curriculum and Instruction", label: "Education Curriculum and Instruction" },
    { value: "Educational Leadership", label: "Educational Leadership" },
    { value: "Ecology and Evolutionary Biology", label: "Ecology and Evolutionary Biology" },
    { value: "Education", label: "Education" },
    { value: "Executive MBA", label: "Executive MBA" },
    { value: "Emergency Medicine", label: "Emergency Medicine" },
    { value: "English", label: "English" },
    { value: "Engineering", label: "Engineering" },
    { value: "Environmental Engineering", label: "Environmental Engineering" },
    { value: "Environmental Sciences", label: "Environmental Sciences" },
    { value: "Educational Psychology", label: "Educational Psychology" },
    { value: "Earth Sciences", label: "Earth Sciences" },
    { value: "European Studies", label: "European Studies" },
    { value: "Environmental Studies", label: "Environmental Studies" },
    { value: "Exploratory", label: "Exploratory" },
    { value: "Foundational Dental Science", label: "Foundational Dental Science" },
    { value: "Field Education (Social Work)", label: "Field Education (Social Work)" },
    { value: "Family Medicine", label: "Family Medicine" },
    { value: "Finance", label: "Finance" },
    { value: "French", label: "French" },
    { value: "Geography", label: "Geography" },
    { value: "German", label: "German" },
    { value: "General and Professional Studies", label: "General and Professional Studies" },
    { value: "Graduate School", label: "Graduate School" },
    { value: "Human Behavior Elective", label: "Human Behavior Elective" },
    { value: "Hartford Consortium For Higher Education", label: "Hartford Consortium For Higher Education" },
    { value: "Healthcare Management and Insurance Studies", label: "Healthcare Management and Insurance Studies" },
    { value: "Human Development and Family Sciences", label: "Human Development and Family Sciences" },
    { value: "Hebrew and Judaic Studies", label: "Hebrew and Judaic Studies" },
    { value: "History", label: "History" },
    { value: "Human Rights", label: "Human Rights" },
    { value: "Individuals, Groups, and Families (Social Work)", label: "Individuals, Groups, and Families (Social Work)" },
    { value: "Italian Literature and Cultural Studies", label: "Italian Literature and Cultural Studies" },
    { value: "Internal Medicine", label: "Internal Medicine" },
    { value: "Institute of Materials Science", label: "Institute of Materials Science" },
    { value: "India Studies", label: "India Studies" },
    { value: "Interdepartmental", label: "Interdepartmental" },
    { value: "International Studies", label: "International Studies" },
    { value: "Irish", label: "Irish" },
    { value: "Independent Study (Social Work)", label: "Independent Study (Social Work)" },
    { value: "Institute for Systems Genomics", label: "Institute for Systems Genomics" },
    { value: "Japanese", label: "Japanese" },
    { value: "Journalism", label: "Journalism" },
    { value: "Kinesiology", label: "Kinesiology" },
    { value: "Korean", label: "Korean" },
    { value: "Landscape Architecture", label: "Landscape Architecture" },
    { value: "Law", label: "Law" },
    { value: "Literatures, Cultures, and Languages", label: "Literatures, Cultures, and Languages" },
    { value: "Linguistics", label: "Linguistics" },
    { value: "Latino and Latin American Studies", label: "Latino and Latin American Studies" },
    { value: "School of Medicine", label: "School of Medicine" },
    { value: "Marine Sciences", label: "Marine Sciences" },
    { value: "Maritime Studies", label: "Maritime Studies" },
    { value: "Mathematics", label: "Mathematics" },
    { value: "Molecular and Cell Biology", label: "Molecular and Cell Biology" },
    { value: "Mechanical Engineering", label: "Mechanical Engineering" },
    { value: "Medical Science", label: "Medical Science" },
    { value: "Management and Engineering for Manufacturing", label: "Management and Engineering for Manufacturing" },
    { value: "Management and Entrepreneurship", label: "Management and Entrepreneurship" },
    { value: "Manufacturing Engineering", label: "Manufacturing Engineering" },
    { value: "Modern Greek", label: "Modern Greek" },
    { value: "Military Science", label: "Military Science" },
    { value: "Marketing", label: "Marketing" },
    { value: "Medical Laboratory Sciences", label: "Medical Laboratory Sciences" },
    { value: "Materials Science and Engineering", label: "Materials Science and Engineering" },
    { value: "Music", label: "Music" },
    { value: "Neurology", label: "Neurology" },
    { value: "Natural Resources and the Environment", label: "Natural Resources and the Environment" },
    { value: "Nursing", label: "Nursing" },
    { value: "Nutritional Sciences", label: "Nutritional Sciences" },
    { value: "OBGYN", label: "OBGYN" },
    { value: "Off Campus", label: "Off Campus" },
    { value: "OMFS", label: "OMFS" },
    { value: "Operations and Information Management", label: "Operations and Information Management" },
    { value: "Orthopaedic", label: "Orthopaedic" },
    { value: "Occupational Safety and Health", label: "Occupational Safety and Health" },
    { value: "Pathobiology", label: "Pathobiology" },
    { value: "Pediatrics", label: "Pediatrics" },
    { value: "Pharmacy - PHAR", label: "Pharmacy - PHAR" },
    { value: "Philosophy", label: "Philosophy" },
    { value: "Pharmacy - PHRX", label: "Pharmacy - PHRX" },
    { value: "Physics", label: "Physics" },
    { value: "Plant Science", label: "Plant Science" },
    { value: "Physiology and Neurobiology", label: "Physiology and Neurobiology" },
    { value: "Political Science", label: "Political Science" },
    { value: "Polymer Science and Engineering", label: "Polymer Science and Engineering" },
    { value: "Policy Practice (Social Work)", label: "Policy Practice (Social Work)" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Public Policy", label: "Public Policy" },
    { value: "Psychiatry", label: "Psychiatry" },
    { value: "Psychological Sciences", label: "Psychological Sciences" },
    { value: "Physical Therapy", label: "Physical Therapy" },
    { value: "Pathology", label: "Pathology" },
    { value: "PTHO", label: "PTHO" },
    { value: "Public Health", label: "Public Health" },
    { value: "Radiology", label: "Radiology" },
    { value: "Research (Social Work)", label: "Research (Social Work)" },
    { value: "Agriculture (RH)", label: "Agriculture (RH)" },
    { value: "Animal Science (RH)", label: "Animal Science (RH)" },
    { value: "Natural Resources and the Environment (RH)", label: "Natural Resources and the Environment (RH)" },
    { value: "Pathobiology (RH)", label: "Pathobiology (RH)" },
    { value: "Plant Science (RH)", label: "Plant Science (RH)" },
    { value: "Agricultural and Resource Economics (RH)", label: "Agricultural and Resource Economics (RH)" },
    { value: "Systems Engineering", label: "Systems Engineering" },
    { value: "Speech, Language and Hearing Science", label: "Speech, Language and Hearing Science" },
    { value: "Sociology", label: "Sociology" },
    { value: "SOWK - Social Work", label: "SOWK - Social Work" },
    { value: "Spanish", label: "Spanish" },
    { value: "Sustainable Plant and Soil Systems", label: "Sustainable Plant and Soil Systems" },
    { value: "Special Topics (Social Work)", label: "Special Topics (Social Work)" },
    { value: "SSW - Social Work", label: "SSW - Social Work" },
    { value: "Statistics", label: "Statistics" },
    { value: "Surgery", label: "Surgery" },
    { value: "Social Work Elective", label: "Social Work Elective" },
    { value: "Transformation", label: "Transformation" },
    { value: "Translation Studies", label: "Translation Studies" },
    { value: "University", label: "University" },
    { value: "Urban and Community Studies", label: "Urban and Community Studies" },
    { value: "Women's, Gender, and Sexuality Studies", label: "Women's, Gender, and Sexuality Studies" }
];
  








const SearchableDropdown = ({filter, setfilter}) => {
  const [selected, setSelected] = useState(null);

  const handleDropdownChange = (selectedOption) => {
    setSelected(selectedOption);
    setfilter(String(selectedOption["value"]));
};

  return (
    <div className="rounded z-1  text-start text-black inline-block relative">
      <Select value={selected}
        onChange={handleDropdownChange}
        options={options}  styles={customStyles} placeholder="Any"> 
        
        </Select>
    </div>
  );
};

export default SearchableDropdown;
