export const classAlias = {
  "Asian and Asian American Studies (AAAS)": "AAAS",
  "Accounting (ACCT)": "ACCT",
  "American English Language Institute (AELI)": "AELI",
  "Africana Studies (AFRA)": "AFRA",
  "Agriculture and Natural Resources (AGNR)": "AGNR",
  "Allied Health Sciences (AH)": "AH",
  "Agriculture, Health and Natural Resources (AHNR)": "AHNR",
  "Air Force Studies (AIRF)": "AIRF",
  "Applied Linguistics and Discourse Studies (ALDS)": "ALDS",
  "Advanced Manufacturing for Energy Systems (AMES)": "AMES",
  "American Studies (AMST)": "AMST",
  "Anesthesiology (ANES)": "ANES",
  "Animal Science (ANSC)": "ANSC",
  "Anthropology (ANTH)": "ANTH",
  "Arabic (ARAB)": "ARAB",
  "Agricultural and Resource Economics (ARE)": "ARE",
  "Arabic and Islamic Studies (ARIS)": "ARIS",
  "Art (ART)": "ART",
  "Art History (ARTH)": "ARTH",
  "American Sign Language (ASLN)": "ASLN",
  "Business Administration (BADM)": "BADM",
  "Basics (Social Work) (BASC)": "BASC",
  "Biological Sciences (BIOL)": "BIOL",
  "Biostatistics (BIST)": "BIST",
  "Business Law (BLAW)": "BLAW",
  "Biomedical Engineering (BME)": "BME",
  "Dental Basic Medical Sciences (BSCI)": "BSCI",
  "Business (BUSN)": "BUSN",
  "Classics and Ancient Mediterranean Studies (CAMS)": "CAMS",
  "Clinical Dental Science (CDSC)": "CDSC",
  "Civil Engineering (CE)": "CE",
  "COOP Education Work Placement (CEWP)": "CEWP",
  "Chemical Engineering (CHEG)": "CHEG",
  "Chemistry (CHEM)": "CHEM",
  "Chinese (CHIN)": "CHIN",
  "Comparative Literary and Cultural Studies (CLCS)": "CLCS",
  "Clinical (CLIN)": "CLIN",
  "Clinical and Translational Research (CLTR)": "CLTR",
  "Cognitive Science (COGS)": "COGS",
  "Communication (COMM)": "COMM",
  "Community Organization (Social Work) (CORG)": "CORG",
  "Computer Science and Engineering (CSE)": "CSE",
  "Dental Science (DENT)": "DENT",
  "Dental Residency and Fellowship Program (DERE)": "DERE",
  "Dermatology (DERM)": "DERM",
  "Diagnostic Genetic Sciences (DGS)": "DGS",
  "Dietetics (DIET)": "DIET",
  "Digital Media and Design (DMD)": "DMD",
  "Dramatic Arts (DRAM)": "DRAM",
  "Statistical Data Science and Analysis (DSDA)": "DSDA",
  "Direct Service Elective (Social Work) (DSEL)": "DSEL",
  "Electrical and Computer Engineering (ECE)": "ECE",
  "Economics (ECON)": "ECON",
  "Education Curriculum and Instruction (EDCI)": "EDCI",
  "Educational Leadership (EDLR)": "EDLR",
  "Ecology and Evolutionary Biology (EEB)": "EEB",
  "Education (EGEN)": "EGEN",
  "Executive MBA (EMBA)": "EMBA",
  "Emergency Medicine (EMED)": "EMED",
  "English (ENGL)": "ENGL",
  "Engineering (ENGR)": "ENGR",
  "Environmental Engineering (ENVE)": "ENVE",
  "Environmental Sciences (ENVS)": "ENVS",
  "Educational Psychology (EPSY)": "EPSY",
  "Earth Sciences (ERTH)": "ERTH",
  "European Studies (ES)": "ES",
  "Environmental Studies (EVST)": "EVST",
  "Exploratory (EXPL)": "EXPL",
  "Foundational Dental Science (FDSC)": "FDSC",
  "Field Education (Social Work) (FED)": "FED",
  "Family Medicine (FMED)": "FMED",
  "Finance (FNCE)": "FNCE",
  "French (FREN)": "FREN",
  "Geography (GEOG)": "GEOG",
  "German (GERM)": "GERM",
  "General and Professional Studies (GPS)": "GPS",
  "Graduate School (GRAD)": "GRAD",
  "Human Behavior Elective (HBEL)": "HBEL",
  "Hartford Consortium For Higher Education (HCHE)": "HCHE",
  "Healthcare Management and Insurance Studies (HCMI)": "HCMI",
  "Human Development and Family Sciences (HDFS)": "HDFS",
  "Hebrew and Judaic Studies (HEJS)": "HEJS",
  "History (HIST)": "HIST",
  "Human Rights (HRTS)": "HRTS",
  "Individuals, Groups, and Families (Social Work) (IGFP)": "IGFP",
  "Italian Literature and Cultural Studies (ILCS)": "ILCS",
  "Internal Medicine (IMED)": "IMED",
  "Institute of Materials Science (IMS)": "IMS",
  "India Studies (INDS)": "INDS",
  "Interdepartmental (INTD)": "INTD",
  "International Studies (INTS)": "INTS",
  "Irish (IRIS)": "IRIS",
  "Independent Study (Social Work) (IS)": "IS",
  "Institute for Systems Genomics (ISG)": "ISG",
  "Japanese (JAPN)": "JAPN",
  "Journalism (JOUR)": "JOUR",
  "Kinesiology (KINS)": "KINS",
  "Korean (KORE)": "KORE",
  "Landscape Architecture (LAND)": "LAND",
  "Law (LAW)": "LAW",
  "Literatures, Cultures, and Languages (LCL)": "LCL",
  "Linguistics (LING)": "LING",
  "Latino and Latin American Studies (LLAS)": "LLAS",
  "School of Medicine (M)": "M",
  "Marine Sciences (MARN)": "MARN",
  "Maritime Studies (MAST)": "MAST",
  "Mathematics (MATH)": "MATH",
  "Molecular and Cell Biology (MCB)": "MCB",
  "Mechanical Engineering (ME)": "ME",
  "Medical Science (MEDS)": "MEDS",
  "Management and Engineering for Manufacturing (MEM)": "MEM",
  "Management and Entrepreneurship (MENT)": "MENT",
  "Manufacturing Engineering (MFGE)": "MFGE",
  "Modern Greek (MGRK)": "MGRK",
  "Military Science (MISI)": "MISI",
  "Marketing (MKTG)": "MKTG",
  "Medical Laboratory Sciences (MLSC)": "MLSC",
  "Materials Science and Engineering (MSE)": "MSE",
  "Music (MUSI)": "MUSI",
  "Neurology (NEUR)": "NEUR",
  "Natural Resources and the Environment (NRE)": "NRE",
  "Nursing (NURS)": "NURS",
  "Nutritional Sciences (NUSC)": "NUSC",
  "OBGYN (OBGY)": "OBGY",
  "Off Campus (OFFC)": "OFFC",
  "OMFS (OMFS)": "OMFS",
  "Operations and Information Management (OPIM)": "OPIM",
  "Orthopaedic (ORTH)": "ORTH",
  "Occupational Safety and Health (OSH)": "OSH",
  "Pathobiology (PATH)": "PATH",
  "Pediatrics (PEDS)": "PEDS",
  "Pharmacy - PHAR (PHAR)": "PHAR",
  "Philosophy (PHIL)": "PHIL",
  "Pharmacy - PHRX (PHRX)": "PHRX",
  "Physics (PHYS)": "PHYS",
  "Plant Science (PLSC)": "PLSC",
  "Physiology and Neurobiology (PNB)": "PNB",
  "Political Science (POLS)": "POLS",
  "Polymer Science and Engineering (POLY)": "POLY",
  "Policy Practice (Social Work) (POPR)": "POPR",
  "Portuguese (PORT)": "PORT",
  "Public Policy (PP)": "PP",
  "Psychiatry (PSCH)": "PSCH",
  "Psychological Sciences (PSYC)": "PSYC",
  "Physical Therapy (PT)": "PT",
  "Pathology (PTHO)": "PTHO",
  "Public Health (PUBH)": "PUBH",
  "Radiology (RADS)": "RADS",
  "Research (Social Work) (RSCH)": "RSCH",
  "Agriculture (RH) (SAAG)": "SAAG",
  "Animal Science (RH) (SAAS)": "SAAS",
  "Natural Resources and the Environment (RH) (SANR)": "SANR",
  "Pathobiology (RH) (SAPB)": "SAPB",
  "Plant Science (RH) (SAPL)": "SAPL",
  "Agricultural and Resource Economics (RH) (SARE)": "SARE",
  "Systems Engineering (SE)": "SE",
  "Speech, Language and Hearing Science (SLHS)": "SLHS",
  "Sociology (SOCI)": "SOCI",
  "SOWK - Social Work (SOWK)": "SOWK",
  "Spanish (SPAN)": "SPAN",
  "Sustainable Plant and Soil Systems (SPSS)": "SPSS",
  "Special Topics (Social Work) (SPTP)": "SPTP",
  "SSW - Social Work (SSW)": "SSW",
  "Statistics (STAT)": "STAT",
  "Surgery (SURG)": "SURG",
  "Social Work Elective (SWEL)": "SWEL",
  "Transformation (TRNS)": "TRNS",
  "Translation Studies (TRST)": "TRST",
  "University (UNIV)": "UNIV",
  "Urban and Community Studies (URBN)": "URBN",
  "Women's, Gender, and Sexuality Studies (WGSS)": "WGSS"
}
