# .github/workflows/log_traffic.yml

name: Log GitHub Traffic

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  log-traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r backend/scripts/requirements.txt

    - name: Run traffic logger
      env:
        GH_TRAFFIC_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
        GITHUB_OWNER: EricAsante3
        GITHUB_REPO: UCONN-course-scheduler
      run: python backend/scripts/traffic.py

    - name: Commit updated log
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add traffic_log.json
        git commit -m "Update traffic log" || echo "No changes to commit"
        git push
